export const STATIC_MAP: string[] = [
  "FFFFFFFFFFFFFTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTMMMTMMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTFFFTTTTTMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFMMMMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFMMMMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFMMMMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFFFFGFFFFFFFFFFFGGFFFFFFFFFFFFFFFFFMMMMMM",
  "FFFFFFFFFFFFFFFFFFFFGGGGGGFFFFFFGGGGGGFFFFFFFFFGGGGGGFFFMMMM",
  "FFFFFFFFFFFFFGGFFFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFFFF",
  "FFFFFFFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "FFFFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "FFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGW",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWW",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWW",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWW",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWW",
  "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWW",
  "GGGGGGGGGGGDDDDDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWW",
  "GGGGGGDDGDDDDDDDDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWW",
  "GGGGDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGWWWWWGGGGGWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGWWWWWWWWWWWWGGWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDDGWWWWWWDDDWWWWWWWWWWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWWWWWWWWWWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWWWWWWWWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWWWWWWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWWWWWWWWWWWWWWWWWW",
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWWWWWWWWWWWWWWWWWW",
];


//para saber si el mapa es correcto

/**console.log('Filas:', STATIC_MAP.length);
console.log('Columnas:', STATIC_MAP[0]!.length);

for (const row of STATIC_MAP) {
  if (row.length !== 60) {
    console.error('Fila inválida:', row.length);
  }
}**/